### ISSUE TITLE
pdfminer error

### ISSUE THREAD

**Issue by parkseonga** [DSC-SCH/home-doctor#1]
pdf url로부터 text를 추출해내고자 하는데 아래와 같은 에러가 발생합니다.
```python
import pandas as pd
import os
import requests

os.chdir(r'C:\Users\a0105\Desktop\[GlobalChallenge]data_rev01')
total = pd.read_csv('최종파일.csv',encoding='cp949')
total = total.dropna(subset=['용법용량'])

from pdfminer.pdfparser import PDFParser, PDFDocument
from pdfminer.pdfinterp import PDFResourceManager, process_pdf
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from io import StringIO
from io import open
from urllib.request import urlopen


def read_pdf_file(pdfFile):
    rsrcmgr = PDFResourceManager()
    retstr = StringIO()
    laparams = LAParams()
    device = TextConverter(rsrcmgr, retstr, laparams=laparams)

    process_pdf(rsrcmgr, device, pdfFile)
    device.close()

    content = retstr.getvalue()
    retstr.close()

    return content


def text_extration(col_, seperator):
    na = []

    for address in col_:
        contents = read_pdf_file(urlopen(address))

        na.append(contents)

    na = ''.join(line.split())
    na2 = na.split(seperator)

    df = pd.DataFrame(list(na2), columns=[seperator]).drop([0])

    return df


effect = text_extration(total['효능효과'],'효능효과')
usage_capacity = text_extration(total['용법용량'], '용법용량')
```

![image](https://user-images.githubusercontent.com/33725048/73819538-2042c480-4833-11ea-810f-084b2bb07b50.png)

효능효과 컬럼의 값들은 다음과 같습니다.
![image](https://user-images.githubusercontent.com/33725048/73819753-9cd5a300-4833-11ea-808b-bed213f28dfe.png)

**Comment by NDjust** [comment]
~~~
def read_pdf_file(pdfFile):
    rsrcmgr = PDFResourceManager()
    retstr = StringIO()
    laparams = LAParams()

    try:
        device = TextConverter(rsrcmgr, retstr, laparams=laparams)
        print(pdfFile)

        process_pdf(rsrcmgr, device, pdfFile)
        device.close()

        content = retstr.getvalue()
        retstr.close()
    except PDFSyntaxError as e:
        print(pdfFile)
        print(e)
        return None
~~~


넘겨주는 url에서 에러가 나는거 같아서 우선 예외처리로 진행 했습니다.

근데 예외처리하면 몇개의 데이터는 날아가는거라 이 부분은 다시 고려를 좀 해야겠네여.

**Comment by parkseonga** [comment]
현재 chromedriver로 다운받은 후 추출하는 과정에서 발생하는 오류는 첨부 문서가 존재하지 않아 발생합니다. 엑셀에서 확인해 본 결과 첨부문서가 실제로 존재하지 않았습니다. 
![image](https://user-images.githubusercontent.com/33725048/74076300-a5f48900-4a5a-11ea-8609-0117324025c5.png)

해당 데이터의 openapi에는 문서의 내용이 적혀있는 부분도 존재하기 때문에 아래와 같은 부분에서 추출해보도록 하겠습니다.
![image](https://user-images.githubusercontent.com/33725048/74076345-e6ec9d80-4a5a-11ea-9141-ea3ab32eed87.png)

**Comment by parkseonga** [comment]
openapi로 추출하고자 했을 때 문제사항은 다음과 같습니다.
1.  각 품목마다 다른 형식으로 효능효과에 대해 설명하고 있음
        - 첫번째 사진이나 세번째 사진은 속성값을 이용해서 효능효과를 설명하는 반면 두번째 사진은 tag에 대한 속성과 text로 효능효과를 설명하고 있기 때문에 각 품목마다 해당 설명을 가져오는 것이 쉽지 않습니다. 
 

![image](https://user-images.githubusercontent.com/33725048/74086502-bc382e80-4ac6-11ea-9a28-8606b6a4f3ed.png)

![image](https://user-images.githubusercontent.com/33725048/74086504-c6f2c380-4ac6-11ea-829a-133ea3ba3df2.png)

![image](https://user-images.githubusercontent.com/33725048/74086524-ed186380-4ac6-11ea-93a0-0b15858ff34d.png)

tag에 관한 속성값을 가져왔을 때 아래와 같이 추출됩니다.
이때, 리스트내 두번째 값은 효능효과에 대한 tag의 text로 부여 설명을 가져와야하지만 특정 패턴이 없어 추출해내기에 어려움을 겪고 있습니다.
![image](https://user-images.githubusercontent.com/33725048/74086599-ad9e4700-4ac7-11ea-8ccc-674b58710169.png)


이를 해결할 좋은 방법이 있을까요?
