### ISSUE TITLE
[Server & App] 서버 통신 관련

### ISSUE THREAD

**Issue by svclaw2000** [DSC-SCH/home-doctor#10]

**Comment by svclaw2000** [comment]
<h4>데이터 송수신</h4>

- 어플 접속 시 데이터 송수신
  - 수정 사항 있는지 확인
  - 수정 사항 있으면 데이터 전송

**Comment by svclaw2000** [comment]
<h4>데이터 송수신</h4>

- UserTB에 user_check 칼럼을 새로 생성하여 업데이트 사항이 있을 때 마다 임의의 토큰 또는 증가만 하는 수로 변경
- 어플에서 데이터 가져올 때 토큰 먼저 확인하고, 어플의 토큰과 서버의 토큰이 일치하지 않으면 데이터 가져오는 식으로 해도 될 것 같음

**Comment by svclaw2000** [comment]
@NDjust 
- CHECK_TB에 관한 API는 특정 사용자의 row만 가져올 수 있게 GET 만 구현하면 됨
- CHECK_TB에 대한 수정은 서버에서만 가능 (수정 진행 시 동시)

**Comment by svclaw2000** [comment]
@NDjust 
<h4>로그인 관련 API 추가</h4>

- 사용자 존재 여부 (회원가입 여부)
  - 해당 uid를 가진 사용자가 DB에 존재하는지 확인

 ``` 
request:
{
    "sns_type": "KAKAO" / "GOOGLE",
    "uid": "user_id"
}

response:
{
    "user_id": -1 (존재X) / user_id (USER_TB의 Primary Key)
}
```

**Comment by svclaw2000** [comment]
@NDjust 
<h4>UPDATE 관련</h4>
- 가능하다면 알람, 라벨 등의 "수정" 작업에서 수정할 칼럼만 입력 받을 수 있게

**Comment by NDjust** [comment]
> @NDjust
> @svclaw2000 
> #### UPDATE 관련
> - 가능하다면 알람, 라벨 등의 "수정" 작업에서 수정할 칼럼만 입력 받을 수 있게

수정할 칼럼이라기 보단 edit 페이지 들어가면 입력된 내용에서 바뀌고 바뀐 값을 받아서 업데이트 하는 방향으로 하면 되지 않을까요?

**Comment by NDjust** [comment]
> @NDjust
> 
> #### 로그인 관련 API 추가
> * 사용자 존재 여부 (회원가입 여부)
>   
>   * 해당 uid를 가진 사용자가 DB에 존재하는지 확인
> 
> ```
> request:
> {
>    "sns_type": "KAKAO" / "GOOGLE",
>    "uid": "user_id"
> }
> 
> response:
> {
>    "user_id": -1 (존재X) / user_id (USER_TB의 Primary Key)
> }
> ```

확인했습니다.

**Comment by NDjust** [comment]
> @NDjust
> 
> * CHECK_TB에 관한 API는 특정 사용자의 row만 가져올 수 있게 GET 만 구현하면 됨
> * CHECK_TB에 대한 수정은 서버에서만 가능 (수정 진행 시 동시)

이 부분이랑 데이터 송수신 부부은 다시 정리 해야할거 같아요. 토큰이랑 같이

**Comment by NDjust** [comment]
@svclaw2000  
[토큰 참고 자료](https://galid1.tistory.com/638)

**Comment by svclaw2000** [comment]
@NDjust 
- 최초 로그인 시 토큰 생성하여 사용자 데이터와 함께 USER_TB에 저장
- 로그인 할 때
  - client -> server {계정 종류, 계정 ID}
  - server -> client {토큰}
- API 사용할 때
  - client -> server {헤더: 토큰}
  - server에서 토큰으로 사용자 확인 후 사용자가 요청한 데이터 반환
- 매니저가 크루의 데이터 요청 할 때
  - client -> server {헤더: 토큰, URL_END:  크루 ID를 파라메터로}
  - server에서 토큰으로 매니저 확인, 해당 토큰을 가진 사용자가 크루ID의 매니저인지 확인
  - 크루ID의 매니저가 맞다고 확인되면, 요청한 데이터 반환

**Comment by svclaw2000** [comment]
> > @NDjust
> > @svclaw2000
> > #### UPDATE 관련
> > 
> > * 가능하다면 알람, 라벨 등의 "수정" 작업에서 수정할 칼럼만 입력 받을 수 있게
> 
> 수정할 칼럼이라기 보단 edit 페이지 들어가면 입력된 내용에서 바뀌고 바뀐 값을 받아서 업데이트 하는 방향으로 하면 되지 않을까요?

넵 알겠습니다!

**Comment by svclaw2000** [comment]
@NDjust 

- 이용약관 API 추가 (회원가입 할 때 사용)
  - GET -> 

```
{
    "status": "",
    "message": "",
    "data" : [
        {
            "title" : "약관이름1",
            "content": "약관 내용"
        },
        {
            "title" : "약관이름2",
            "content": "약관 내용"
        },
        ...
    ]
}
```

**Comment by svclaw2000** [comment]
@NDjust 
- 문의사항 API 추가
  - 문의 내용
  - 답변 회신 이메일

**Comment by svclaw2000** [comment]
@NDjust 
- 회원가입 (request body)
  - password, brand2_idx 제거
- 로그인 (response body)
  - password 제거

**Comment by svclaw2000** [comment]
@NDjust 
- 회원가입 (request)
  - 전화번호 프론트에서 전처리 후 숫자만으로 된 데이터 전송

**Comment by svclaw2000** [comment]
@NDjust 
- 회원가입
  - response status 성공 201로 되어있는데 확인 바람
  - 가능하면 "성공"에 대한 status는 200으로 통일 바람

**Comment by NDjust** [comment]
@svclaw2000 위에서 추가 문의하신 내용 중 문의사항은 로직을 다시 생각해봐야해서 문의사항 빼고 만들어 놨습니다. 


그리고 내일 추가로 CHECK_TB 만들어서 업데이트 통신하는거는 같이 이야기 해봐요.


[위 내용 반영한 API 명세서 업데이트 본](https://www.notion.so/nathanh/API-aa1091f156704248a174c19cde60f621)

**Comment by svclaw2000** [comment]
> @svclaw2000 위에서 추가 문의하신 내용 중 문의사항은 로직을 다시 생각해봐야해서 문의사항 빼고 만들어 놨습니다.
> 
> 그리고 내일 추가로 CHECK_TB 만들어서 업데이트 통신하는거는 같이 이야기 해봐요.
> 
> [위 내용 반영한 API 명세서 업데이트 본](https://www.notion.so/nathanh/API-aa1091f156704248a174c19cde60f621)

넵

**Comment by svclaw2000** [comment]
- 연동 목록 조회에 `이름` 추가
- 연동 추가할 때 같은 사람이 코드 만료되기 전에 또 요청하면 어떻게 처리할지 확인
- 케어 연동 (코드 전송) 수정
  - manager는 연동 요청을 보낸 사람 (코드를 전송한 사람)
  - reiceiver는 연동 코드를 생성한 사람
  - 따라서 요청 바디에는 {"code": "크루로 등록될 사람이 생성한 코드"}
- 알람 정보 response에는 무조건 처방전 정보는 빼고, 프론트에서 필요한 경우에만 요청하도록
- 연동한 유저 알람 리스트 가져올 때 /connect/receiver/alarm/{crew_user_id} 로 GET 할 수 있도록
- 알람 등록 성공 response - data 에 저장된 알람의 alarm_id 반환
