### ISSUE TITLE
[의약 Data] 의약정보 테이블 필드

### ISSUE THREAD

**Issue by NDjust** [DSC-SCH/home-doctor#4]
1. 품목기준코드(품목일련번호)
2. 품목명
3. 효능효과
4. 저장방법
5. 유효기간
6. 용법용량 (**위 필드들은 의약품 상세조회(OPENAPI) 데이터)
7. 의약품 부작용(22. 의약품 부작용 정보)
8. 큰제품이미지(11. 공공데이터개방_낱알식별목록)
9. 주의사항(DUR유형별 품목 현황 데이터로부터 주의사항 필드 생성)

**Comment by parkseonga** [comment]
필드 | type | 비고
-- | -- | --
품목명 | varchar(80) |  primary key
효능효과 | text |  
유효기간 | varchar(50) |  
저장방법 | text |  
용법용량 | text |  
부작용 | text |  
분류명 | varchar(100) |  
특정연령대금기품목 | varchar(150) |  
임부주의 | varchar(150) |  
분할주의 | varchar(150) |  
투여기간주의 | varchar(150) |  
효능군중복주의 | varchar(150) |  
용량주의 | varchar(150) |  
노인금기 | varchar(150) |  
이미지 url | varchar(100) |  

@NDjust 품목기준코드의 경우 품목명 기준 여러 개의 품목기준코드를 가질 수 있는데 특정 번호만 가져오는 것이 애매하기 때문에 품목명을 primary key로 수정하였습니다.

**Comment by parkseonga** [comment]
필드| type|
-- | -- | 
병용품목명 | varchar(80) |
비고 | text |  
금기내용 | text |  
품목명 | varchar(80) |
