### ISSUE TITLE
[의약 Data] 추가 필드 생성 및 데이터 전처리

### ISSUE THREAD

**Issue by NDjust** [DSC-SCH/home-doctor#5]
[20.02.07] To Do

- [x] pdf다운로드하여 파일에서 글자 추출(효능효과, 용법용량)
- [x] 공공데이터_낱알식별정보와 의약품 상세 조회 결합
- [x] 의약품 부작용 필드 생성 
     - 주성분 필드 구분자 기호 파악
     - 마약류 데이터 다운받은 후 의약품 부작용 데이터와 다른 품목이 있으면 추가로 결합
- [x] 주의사항 필드 생성(dur 유형별 품목 현황 데이터정제)
    - dur 유형별 품목 현황 데이터의 금기내용 필드를 이용하여 생성

(참고)

- 효능효과, 용법용량이 명시되어 있지 않는 품목의 경우 삭제
- 제품이미지가 없는 품목 유지(이미지가 없는대로 게시?삭제?)
- 이야기해보기

**Comment by parkseonga** [comment]
제품이미지가 없는 품목의 경우 이미지가 없는 것들을 삭제하는 것보다 따로 첨부되지 않도록 하는 것이 좋을 것 같은데 어떻게 생각하시나요?

**Comment by NDjust** [comment]
@parkseonga 네 따로 첨부 안해도 무방할거 같습니다.

**Comment by NDjust** [comment]
주의사항 필드 생성 완료.

**Comment by parkseonga** [comment]
pdf 파일에서 텍스트 추출할 때 데이터 날아가신다고 하셨는데 첨부파일이 없어서 데이터가 날라가는 건가요?

**Comment by NDjust** [comment]
@parkseonga 아뇨 저는 그냥 라이브러리 상에서 오류가 계속 났어요!

+ 2번은 내일 제가 진행해보겠습니다. 1번 완료되시면 공유해주세요!

**Comment by NDjust** [comment]
@parkseonga 주성분수에 맞춰 주성분을 구분자에 맞춰 나눌려고 진행중인데, 몇몇개 주성분은 구분자가 어떤식으로 알아봐야할지 명확하지 않아서 어떻게 처리하면 좋을지 의견 부탁드립니다.
<img width="415" alt="image" src="https://user-images.githubusercontent.com/47904523/74096757-3b207c00-4b46-11ea-8a60-1f0ab41945d7.png">

추가로 주성분 필드('/' 구분자로 나눈 후)와 주성부수와 일치하지 않은 데이터는 총 131개로 그리 많지 않은데 우선 스킵하고 데이터 베이스 저장형태를 빠르게 만들고 데이터 앱 서빙으로 진행을 하는 것은 어떨까요?? (기한이 그리 많이 남지 않아서!)

**Comment by parkseonga** [comment]
네 알겠습니다! 현재 효능효과 데이터는 네이버 의약품사전에서 크롤링하고 있습니다.

**Comment by parkseonga** [comment]
전처리된 데이터 보내주시면 오늘 데이터 베이스에 저장해놓겠습니다.

**Comment by NDjust** [comment]
@parkseonga 최대한 빨리 하겠습니다. 이미지랑 효과 효능은 마무리 되셨나요??

**Comment by parkseonga** [comment]
@NDjust
1차로 작업이 끝난 상태이며 pdf를 통해 추출하는 작업을 재실행시키고 있습니다.
