### ISSUE TITLE
[의약 Data] 범용금기 데이터 저장

### ISSUE THREAD

**Issue by NDjust** [DSC-SCH/home-doctor#6]
현재 의약품 데이터 디비에 저장을 했는데 추가로 범용금기 데이터 저장은 어떤식으로 하고 의약품 데이터랑 어떻게 결합해서 제공할지 의견 부탁드립니다.

**Comment by parkseonga** [comment]
병용금기 데이터를 현재 전처리를 완료했으나 여전히 중복되는 값들이 존재하여 순번으로 primary key를 처리할 예정입니다. 의약품 데이터와는 외래키로 품목명을 연결하고자 합니다. 

추가로 의약품 데이터 중 품목명은 같으나 품목일련번호가 다른 경우 효능효과, 용법용량 등의 내용 또한 다른지 확인해보고 다르다면 최근 날짜로 허가된 품목을 가져오도록 전처리할 예정입니다.

**Comment by parkseonga** [comment]
병용금기 데이터를 현재 전처리를 완료했으나 여전히 중복되는 값들이 존재하여 순번으로 primary key를 처리할 예정입니다. 의약품 데이터와는 외래키로 품목명을 연결하고자 합니다.
