### ISSUE TITLE
[DB] 테이블 생성

### ISSUE THREAD

**Issue by parkseonga** [DSC-SCH/home-doctor#7]
`2020.02.12`  회의내용

#### search DB
- [의약정보 테이블](https://github.com/DSC-SCH/home-doctor/issues/4)

#### social_login DB
- 등록되어 있는 회원의 모든 정보 가져옴

#### 연동 DB
ex)

_ID | 케어_ID
-- | --
001 | 002\| 003\| 004
002 | 001\| 005\| 006

#### 알람 DB
- _ID, TITLE, TIMES, REPEAT, ALARM, START, END
#### 라벨 DB
- _ID, TITLE, COLOR

#### 알람 DB
- _ID, TITLE, TIMES, REPEAT, ALARM, START, END
#### 라벨 DB
- _ID, TITLE, COLOR

**Comment by NDjust** [comment]
<img width="756" alt="DB설계" src="https://user-images.githubusercontent.com/47904523/74511697-eae05a00-4f49-11ea-8012-0536d4995b16.png">
1차로 db 설계를 하긴 했는데 각 디비별 그리고 테이블별 정의를 명확히 같이 정하고 가야할거 같네요. 

위 그림 한번만 참고해주시고 피드백과 각 테이블별 필드에 대해서 날잡아서 이야기해봐요:smile:

@parkseonga @svclaw2000

**Comment by parkseonga** [comment]
medicine_info table에서 primary key를 품목명으로 변경하고 분류명 필드를 추가해야합니다.
@NDjust

**Comment by svclaw2000** [comment]
prescription 테이블은 어떤 테이블인가요?

**Comment by parkseonga** [comment]
처방전 테이블로 추측됩니다!

**Comment by parkseonga** [comment]
처방전 테이블에 알람과 라벨을 포함시켜야하나요?

**Comment by svclaw2000** [comment]
지금 수업중이라 이따 들어가서 테이블 정리 한 번 해보고 제가 설계할 수 있는 부분은 코멘트 달게요!

**Comment by svclaw2000** [comment]
나단님의 테이블에서 어플에 맞게 조금 수정하고 양방향으로 FK 걸린 것과 불필요할 것으로 예상된 FK를 제거하고 사용자, 라벨, 처방전 TB를 만들었습니다. 확인해주세요!  

<h3>USER_TB</h3>

| Column Name | Type | Option | Example |
|-|-|-|-|
|_id|INTEGER|(PK,AI)||
|user_name|VARCHAR(20)|||
|birthday|CHAR(10)||0000-00-00|
|gender|INTEGER(1)||1(M)/2(F)|
|phone_num|VARCHAR(15)|||
|care_list|TEXT|||

<h3>LABEL_TB</h3>

| Column Name | Type | Option | Example |
|-|-|-|-|
|_id|INTEGER|(PK,AI)||
|label_user|INTEGER|(FK->USER_TB$_id)||
|label_title|VARCHAR(16)|(NN)||
|label_color|CHAR(7)|(NN)|#000000|

<h3>PRESCRIPTION_TB</h3>

| Column Name | Type | Option | Example |
|-|-|-|-|
|_id|INTEGER|(PK,AI)||
|pre_title|VARCHAR(64)|||
|pre_content|VARCHAR(512)|||
|pre_image|LONGBLOB|||
|pre_user|INTEGER|(FK->USER_TB$_id)||
|pre_label|INTEGER|(FK->LABEL_TB$_id)||
|alarm_title|VARCHAR(64)|(NN)||
|alarm_start_dt|CHAR(10)|(NN)|0000-00-00|
|alarm_end_dt|CHAR(10)|(NN)|0000-00-00|
|alarm_times|VARCHAR(128)|(NN)|["09:00",...]|
|alarm_repeats|VARCHAR(32)|(NN)|[1,...,7]|
|alarm_enabled|INTEGER(1)|(NN)|0/1|

- **NN: NOT NULL**
- **PK: PRIMARY KEY**
- **AI: AUTO_INCREMENT**
- **FK: FOREIGN KEY**
  
@NDjust  (처방전 | 알람),  (사용자 | 연동 TB)들을 따로 나눈 이유가 있나요?? 만약 꼭 필요한 것이 아니라면 알려주세요! 나중에 가져다 쓸 때 JOIN이 많이 사용될 것 같아서 뺐습니당

**Comment by NDjust** [comment]
@svclaw2000 처방전| 알람은 한번 이야기 하고 같이 묶으려 했었어요. 우선 위 피드백 주신거 참고해서 구성해볼게요!

**Comment by NDjust** [comment]
DB 2차 수정 
- 피드백 반영해서 2차 수정했고, 추가로 변경사항이나 추가할 부분 말씀해주세요.

추가 질문사항
- @parkseonga 그리고 저희 병용금기 의약품에 대한 정보를 제공할때는 TB들 간의 관계를 두지 않고 where 문으로 서빙하는게 나을까요?? 아님 FK로 묶을까요??
- @svclaw2000 User TB에 처방전 list가 담긴 field가 필요할거 같아 추가했는데 괜찮을까요?

![image](https://user-images.githubusercontent.com/47904523/74625222-ece72a80-518e-11ea-914a-c1b9a9a53e82.png)

**Comment by NDjust** [comment]
user_info 에서 pre_list 필드를 없애고 pre_user에서 foreign key로 user_info id 값을 가져옴.(1대 다 관계)

**Comment by parkseonga** [comment]
병용금기에 고유값만을 가지는 필드가 없기 때문에 foreign key로 연결하는게 좋을 것 같아요!

**Comment by parkseonga** [comment]
저희 user_info 에 password가 빠져있어요! 
@svclaw2000 @NDjust

**Comment by parkseonga** [comment]
또한 저희가 탈퇴 후 보관할 비개인정보가 있는지도 궁금합니다!

**Comment by NDjust** [comment]
![DB Design](https://user-images.githubusercontent.com/47904523/75402930-8231ae00-5949-11ea-9ab1-ff0f5aa26099.png)


@svclaw2000 추가 했어유

**Comment by svclaw2000** [comment]
@NDjust 
- ImageTB - user 1 : * image --> alarm 1 : * image
- AlarmTB - df --> dt (오타인지 다른 뜻이 있는건지 잘 모르겠지만 확인 바람)
- AlarmTB - alarm_created_dt, alarm_edited_dt 추가
- AlarmTB - alarm_content는 어디에 사용되는 칼럼인가요?
- CareTB - care_date는 어디에 사용되는 칼럼인가요?

**Comment by NDjust** [comment]
@svclaw2000 
- image TB 그럼 해당 알람에 여러개의 이미지가 들어올 수 있겠네요?
- df -> dt 오타 맞음
- 추가 확인
- 알람 설명 추가하는 내용입니다:) ui에는 이게 없었나요? 확인 해보고 수정하겠습니다.
- 연동 되었을때 날짜입니다.


현재 디비는 계속 수정중이며 수정 후 테이블과 매핑관계 업데이트 하겠습니다.

**Comment by svclaw2000** [comment]
처방전 / 검사지 등이 두 페이지 이상으로 넘어갈 수도 있을 경우도 고려하고, 알람과 링킹하기 위해서 입니다!

**Comment by svclaw2000** [comment]
- connect_code, prescription_image, user, care에서 date --> dt 로 통일

**Comment by NDjust** [comment]
@svclaw2000 

타입 변경
ALARM_TB.enabled
->  문자열로 ( ENABLE, CANCEL  두가지 형태)

USER_TB.sns_type
-> 문자열로 (KAKAO, GOOGLE 두가지 형태)
