### ISSUE TITLE
도메인 & 엔티티 설계

### ISSUE THREAD

**Issue by NDjust** [DSC-SCH/home-doctor#9]
# 도메인 분석 설계

### 회원 기능

---

- 회원 등록 기능
- 회원 조회 기능
- 회원 정보 수정 기능
- 케어 기능
- 탈퇴 기능

### 회원 연동 기능

---

- 등록 기능
- 수정 기능
- 조회 기능
- 인증 기능

### 약 알람 기능

---

- 알람 등록 기능
    - 라벨 설정 기능
    - 날짜 설정 기능
    - 시간 설정 기능
    - 처방전 사진 등록 기능
        - 사진 조회 기능
- 수정 기능
- 조회 기능

### 검색 기능

---

- 약 조회 기능
    - 단순 약 검색.

### 기타 요구 사항

---

- 알람은 ON / OFF 기능 필요

# 도메인 모델과 테이블 설계

---

![Untitled (1)](https://user-images.githubusercontent.com/47904523/75223490-e89fba80-57e9-11ea-9010-df8cf894ce2e.png)

회원, 연동, 연결 코드 관계

- 한명의 회원이 여러명을 케어할 수 있으니 일대다 관계.
- 하나의 유저가 한번의 하나의 연결 코드를 생성할 수 있으니 일대일 관계

약 알람, 라벨, 회원 관계

- 회원은 다양한 약 알람을 가지고 있을 수 있다. 그래서 약 알람 테이블과 회원 테이블은 다대일 관계로 매핑
- 라벨 하나의 여러 개의 처방전에서 사용될 수 있으니 라벨과 처방전 테이블은 일대다 관계
- 하나의 유저는 여러 개의 라벨을 사용할 수 있으므로 라벨과 회원정보는 다대일 관계

#### Reference 
- https://developers.kakao.com/docs/restapi/kakaotalk-api
- https://github.com/ToyCalendar/ToyCalendar_Server/wiki/DB-설계

**Comment by NDjust** [comment]
@parkseonga @svclaw2000 
회원 기능과 연동 기능은 분리하는게 좋을거 같아서 분리 했어요. 연동 조회 등록 수정 기능이 있어서요. 


합치는게 좋다면 코멘트 남겨주세요:)

**Comment by svclaw2000** [comment]
@NDjust 테이블을 분리하나 합치나 크게 차이는 없을 것 같습니다!

**Comment by NDjust** [comment]
@svclaw2000 위에 연동시 연결 코드에 대한 테이블도 필요해서 저런식으로 따로 뺏어요. 피드백 받으면서 점점 효율적으로 구성해볼게요!

그리고 기능적인면 빠진 부분 피드백 부탁드려요

**Comment by svclaw2000** [comment]
@NDjust 우선은 괜찮은 것 같습니다!

**Comment by svclaw2000** [comment]
@NDjust alarm_info 1 : * 사진 의 DB가 추가되어야 할 것 같습니다!

**Comment by NDjust** [comment]
<img width="659" alt="스크린샷 2020-02-26 오후 10 31 29 복사본" src="https://user-images.githubusercontent.com/47904523/75349562-61853c00-58e8-11ea-9b60-42b4131278cb.png">

**Comment by NDjust** [comment]
<img width="534" alt="image" src="https://user-images.githubusercontent.com/47904523/76162075-0cb1b300-617d-11ea-8987-6c40674f1e8b.png">


@svclaw2000 관계 매핑 최종 1차 본입니다. 이상한 부분 있으면 피드백 해주세요:)

**Comment by svclaw2000** [comment]
@NDjust 
- https://www.notion.so/e7e7ed4413ea488eb317a3eddd031370?v=d79fdcd788394514b276ffbc63049943
  - 각 테이블의 수정 횟수(수정 될 때마다 +1)를 저장하는 테이블
  - 서버와 어플 모두에서 만들어 업데이트 필요를 확인하는 용도
  - 어플에서 특정 테이블의 수정 횟수가 서버 기록보다 작을 시 해당 특정 테이블 다운로드

- 업데이트 된 관계 매핑으로 제 명세서 수정했습니다!

**Comment by svclaw2000** [comment]
@NDjust 
- USER_TB
  - kakao_id, google_id -> sns_uid (두 가지 모두 로그인 하는 사용자 없음)

**Comment by svclaw2000** [comment]
@NDjust 
- IMAGE_TB
  - _id -> image_id

**Comment by NDjust** [comment]
![image](https://user-images.githubusercontent.com/47904523/76721102-3755ca00-6782-11ea-9cb9-06585ac85964.png)
